# SPDX-FileCopyrightText: 2017 Free Software Foundation Europe e.V. <https://fsfe.org>
# 
# SPDX-License-Identifier: GPL-3.0-or-later

baseurl = "https://publiccode.eu"
title = "Public Money, Public Code"
theme = "hugo-creative-theme"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableGitInfo = true
#disableKinds = ["taxonomy"]
disableKinds = ["taxonomy", "term"]
timeout = "30s"

# Static strings shared by all languages – these are not to be translated!
[params.static]
  url         = "https://publiccode.eu"
  slogan_1    = "Public Money"
  slogan_2    = "Public Code"
  promoLink   = "https://fsfe.org/promo#pmpc"
  language    = "Language"

[params.static.meta]
  author        = "Free Software Foundation Europe (FSFE)"
  previewImage  = "img/share-graphics/why.png"
  fbPageID      = "336939393138306"
  twitterUser   = "@fsfe"

# Arguments
[[params.arguments.list]]
  no          = "1"
  icon        = "fa-eur"
[[params.arguments.list]]
  no          = "2"
  icon        = "fa-handshake-o"
[[params.arguments.list]]
  no          = "3"
  icon        = "fa-users"
[[params.arguments.list]]
  no          = "4"
  icon        = "fa-lightbulb-o"

# Resources
[[params.resources.list]]
  no      = 1
  img     = "img/resources/foi.jpg"
  link    = "https://fsfe.org/tags/tagged-pmpc"
  target  = "_blank"
[[params.resources.list]]
  no    = 2
  img   = "img/resources/brochure.jpg"
  link  = "https://fsfe.org/activities/publiccode/brochure"
  target  = "_blank"
[[params.resources.list]]
  no    = 3
  img   = "img/resources/write.jpg"
  link  = "/media"
  target  = "_self"


# === TRANSLATIONS ===
[Languages]
  [Languages.ca]
    languageCode  = "ca"
    languageName  = "Català"

  [Languages.cs]
    languageCode  = "cs"
    languageName  = "Čeština"

  [Languages.da]
    languageCode  = "da"
    languageName  = "Dansk"

  [Languages.de]
    languageCode  = 'de'
    languageDirection = 'ltr'
    languageName  = 'Deutsch'

  [Languages.el]
    languageCode  = "el"
    languageName  = "Ελληνικά"

  [Languages.en]
    languageCode = "en"
    languageName = "English"
    languageDirection = 'ltr'
    weight = 1

  [Languages.eo]
    languageCode  = "eo"
    languageName  = "Esperanto"

  [Languages.es]
    languageCode  = "es"
    languageName  = "Español"

  [Languages.fr]
    languageCode  = "fr"
    languageName  = "Français"

  [Languages.hr]
    languageCode  = "hr"
    languageName  = "Hrvatski"

  [Languages.hy]
    languageCode  = "hy"
    languageName  = "Հայերէն"

  [Languages.hu]
    languageCode  = "hu"
    languageName  = "Magyar"

  [Languages.it]
    languageCode  = "it"
    languageName  = "Italiano"

  [Languages.ja]
    languageCode  = "ja"
    languageName  = "日本語"

  [Languages.nb]
    languageCode  = "nb"
    languageName  = "Norsk (bokmål)"

  [Languages.nl]
    languageCode  = "nl"
    languageName  = "Nederlands"

  [Languages.pl]
    languageCode  = "pl"
    languageName  = "Polski"

  [Languages.pt]
    languageCode  = "pt"
    languageName  = "Português"

  [Languages.ru]
    languageCode  = "ru"
    languageName  = "Русский"

  [Languages.sl]
    languageCode  = "sl"
    languageName  = "Slovenščina"

  [Languages.sq]
    languageCode  = "sq"
    languageName  = "Shqip"

  [Languages.sv]
    languageCode  = "sv"
    languageName  = "Svenska"

  [Languages.tr]
    languageCode  = "tr"
    languageName  = "Türkçe"

  [Languages.zh-TW]
    languageCode  = "zh-TW"
    languageName  = "正體中文（臺灣）"

  [Languages.zh-HK]
    languageCode  = "zh-HK"
    languageName  = "繁體中文（香港）"
